---
- name: "Download Logstash's deb"
  get_url:
    #403
    #url: "https://artifacts.elastic.co/downloads/logstash/logstash-{{ logstash_version }}-amd64.deb"
    url: https://ntl.run0ut.ru/cicd/logstash-{{ logstash_version }}-amd64.deb
    dest: "/tmp/logstash-{{ logstash_version }}-amd64.deb"
    mode: 0755
  register: download_logstash
  until: download_logstash is succeeded

#- name: Ensure Java is installed.
#  become: true
#  apt: deb="java-1.8.0-openjdk" 

- name: Install Logstash
  become: true
  apt: deb="/tmp/logstash-{{ logstash_version }}-amd64.deb" 

- name: Configure startup options
  become: true
  template:
    src: "startup.options.j2"
    dest: "/etc/logstash/startup.options"
    mode: 0644
#
#- name: Create startup scripts
#  become: true
#  command:
#    cmd: /usr/share/logstash/bin/system-install /etc/logstash/startup.options systemd

- name: Create Logstash configuration files.
  become: true
  template:
    src: "{{ item }}.j2"
    dest: "/etc/logstash/conf.d/{{ item }}"
    mode: 0644
  with_items:
    - simple_config.conf
  notify: restart Logstash
